export const GET_REGISTRATION_LOADING = 'GET_REGISTRATION_LOADING';
export const GET_REGISTRATION_LOADED = 'GET_REGISTRATION_LOADED';
export const GET_REGISTRATION_FAILED = 'GET_REGISTRATION_FAILED';

export const LOGGED_OUT = 'LOGGED_OUT';

export const GET_AUTH_LOADING = 'GET_AUTH_LOADING';
export const GET_AUTH_LOADED = 'GET_AUTH_LOADED';
export const GET_AUTH_FAILED = 'GET_AUTH_FAILED';

export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_LOADED = 'GET_USER_LOADED';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const SET_USER_DATA_LOADING = 'SET_USER_DATA_LOADING';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_DATA_FAILED = 'SET_USER_DATA_FAILED';

export const GET_FORGOT_PASSWORD_LOADING = 'GET_FORGOT_PASSWORD_LOADING';
export const GET_FORGOT_PASSWORD_FAILED = 'GET_FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_LOADING = 'RESET_PASSWORD_LOADING';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';