export const GET_INGREDIENTS_LOADING = 'GET_INGREDIENTS_LOADING';
export const GET_INGREDIENTS_LOADED = 'GET_INGREDIENTS_LOADED';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const SELECT_INGREDIENT_BUN = 'SELECT_INGREDIENT_BUN';
export const INCREASE_INGREDIENT = 'INCREASE_INGREDIENT';
export const DECREASE_INGREDIENT = 'DECREASE_INGREDIENT';
export const RESET_SELECTED_INGREDIENTS = 'RESET_SELECTED_INGREDIENTS';