export const CREATE_ORDER_LOADING: 'CREATE_ORDER_LOADING' = 'CREATE_ORDER_LOADING';
export const CREATE_ORDER_LOADED: 'CREATE_ORDER_LOADED' = 'CREATE_ORDER_LOADED';
export const CREATE_ORDER_FAILED: 'CREATE_ORDER_FAILED' = 'CREATE_ORDER_FAILED';
export const RESET_ORDER_DETAILS: 'RESET_ORDER_DETAILS' = 'RESET_ORDER_DETAILS';